version: '3.8'

services:
  database:
    image: postgres:15
    container_name: postgres_prisma_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      postgres_prisma_db: prisma-with-postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: express_prisma_api
    depends_on:
      - database
    environment:
      - DATABASE_URL=postgresql://postgres:root@database:5432/prisma-with-postgres?schema=public
      - PORT=3000
    ports:
      - "3000:3000"
      - "3006:3000" # http://localhost:3006/api/authors/add-author
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: [ "sh", "-c", "npx prisma generate && node src/server.js" ]
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9091:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml

volumes: 
  postgres_data: