global:
  scrape_interval: 5s # by default every 15s

scrape_configs:
  - job_name: "express_prisma_api"
    static_configs:
      - targets: ["express_prisma_api:3000"] # Target the express_prisma_api service inside Docker
